---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: xebia-email-signature
      Description: 'xebia-email-signature builder'
      ServiceRole: !Ref 'ProjectRole'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REGISTRY_HOST
            Type: PLAINTEXT
            Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com'
          - Name: AWS_REGION
            Type: PLAINTEXT
            Value: !Ref 'AWS::Region'

      Source:
        Type: GITHUB
        Location: https://github.com/OblivionCloudControl/xebia-email-signature.git
        BuildSpec: .buildspec.yaml
        GitCloneDepth: 0

      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: "^refs/heads/main$"

  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
            Condition: {}
      Path: /
      Policies:
        - PolicyName: WriteToContainerRegistry
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource:
                  - !GetAtt Repository.Arn

        - PolicyName: DeployStackPermission
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - '*'
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  - !GetAtt CloudformationRole.Arn

        - PolicyName: WriteToLogGroup
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/xebia-email-signature:*'

  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudformationRole
      Path: /
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationAdministrator
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 'apprunner:*'
                Resource: '*'
              - Effect: Allow
                Action: 'iam:*'
                Resource: '*'
              - Effect: Allow
                Action: 'route53:*'
                Resource: '*'
              - Effect: Allow
                Action: 'cloudfront:*'
                Resource: '*'
              - Effect: Allow
                Action: 'acm:*'
                Resource: '*'
              - Effect: Allow
                Action: 'lambda:*'
                Resource: '*'

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: xebia-email-signature

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${Project}'
      RetentionInDays: 7
